<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "t3sbootstrap"
 *
 * Auto generated by Extension Builder 2014-11-27
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array (
	'title' => 'Bootstrap Components',
	'description' => 'Startup extension to use bootstrap 3 classes and components out of the box. Suitable for small projects to save development time. Works with dyncss - Less Parser! Example and info: www.t3sbootstrap.de',
	'category' => 'templates',
	'version' => '3.2.43',
	'state' => 'stable',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearcacheonload' => 0,
	'author' => 'Helmut Hackbarth',
	'author_email' => 'typo3@t3solution.de',
	'author_company' => 't3solution',
	'constraints' =>
	array (
		'depends' =>
		array (
			'typo3' => '7.6.0-8.7.99',
			'gridelements' => '7.0.0-8.7.99',
			'fluid_styled_content' => '7.6.0-8.7.99',
		),
		'conflicts' =>
		array (
			'fluidpages' => '0.0.0-99.99.99',
		),
		'suggests' =>
		array (
		),
	),
	'autoload' => array(
		'psr-4' => array(
			'T3SBS\\T3sbootstrap\\'=> 'Classes'
		),
	),
);
